<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Buildalyzer" />
    <PackageReference Include="Mono.Cecil" />
    <PackageReference Include="ResXResourceReader.NetStandard" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Microsoft.CodeAnalysis.Common" />
    <PackageReference Include="StreamJsonRpc" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Stryker.Abstractions\Stryker.Abstractions.csproj" />
    <ProjectReference Include="..\Stryker.MSBuildHost.Contracts\Stryker.MSBuildHost.Contracts.csproj" />
  </ItemGroup>

</Project>
